Feat includes not annotated logos in search
openfoodfacts/hunger-games pull request #267
Opened 2022-10-11 16:55 UTC by alexfauquette

### Fixes bug(s)
- Fix #262

![image](https://user-images.githubusercontent.com/45398769/195136766-307b87fe-93b0-426f-867d-761e2546d1c7.png)

See the issue comment. I'm not sure about how the API responds when `annotated` parameter is not provided

2022-10-13 09:03 UTC, raphael0202 commented on src/robotoff.ts
>      return axios.get(`${ROBOTOFF_API_URL}/images/logos`, {
```suggestion
    return axios.get(`${ROBOTOFF_API_URL}/images/logos/search`, {
```

2022-10-13 09:04 UTC, raphael0202 requested changes
see suggestion about new search route

2022-10-13 11:07 UTC, alexfauquette commented
Should be merged after robotof deployment of the search route. For now, this returns 404.

https://robotoff.openfoodfacts.org/api/v1/images/logos/search/?barcode=3560071212810&count=25

2022-10-14 07:32 UTC, raphael0202 commented
It's now merged but not deployed. I plan to deploy next Monday.

2022-10-14 15:38 UTC, alexfauquette commented
Nice, if you want you can merge it after deploy is done 👍

Merging on master triggers the deploy github action

2022-10-17 10:56 UTC, raphael0202 commented
Merging this as the Robotoff update has been deployed to production

2022-10-17 11:01 UTC, raphael0202 approved these changes

2022-10-17 11:01 UTC, merged